production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: drtopov4
  username: agrantmysql1
  password: Climbing111
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: drtopov4_development
  username: root
  password:
  socket: /tmp/mysql.sock