production:
  adapter: mysql2
  encoding: utf8
  database: drtopov4
  username: agrantmysql1
  password: Climbing111
  host: mysql.drtopo.co
  socket: 

development:
  adapter: mysql2
  encoding: utf8
  database: drtopov4_development
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock
  
test:
  adapter: mysql2
  encoding: utf8
  database: drtopov4_test
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock